apiVersion: v1
kind: Service
metadata:
  name: {{ include "billtitleindex-chart.fullname" . }}
  labels:
    {{- include "billtitleindex-chart.labels" . | nindent 4 }}
  annotations:
    {{- include "billtitleindex-chart.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5555
      targetPort: 5555
      protocol: TCP
      name: flower-5555
  selector:
    {{- include "billtitleindex-chart.selectorLabels" . | nindent 4 }}
