version: '3.3'

services:
  # PostgreSQL
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    #    networks:
    #      - main
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: on-failure

  # Elasticsearch
  es01:
    container_name: es01
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    #    networks:
    #      - main
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data1:/var/log/data
    restart: on-failure

  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    #    networks:
    #      - main
    restart: on-failure

  # FastAPI
  api:
    hostname: api
    container_name: api
    env_file:
      - .env
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - es01
    volumes:
      - .:/app
    #    networks:
    #      - main
    restart: on-failure

  # celery worker
  celery_worker:
    hostname: celery_worker
    env_file:
      - .env
    build: .
    command: sh -c "celery -A billtitleindex worker -l info -E -B"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/app
    restart: on-failure

#networks:
#  main:

volumes:
  postgresql-data: